server:
  port: 8889
  servlet:
    context-path: /sugarcoat

#localhost:8889/sugarcoat/doc.html

spring:
  application:
    name: sugarcoat
  jackson:
    time-zone: GMT+8
  # 连接数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池设置
    hikari:
      # 最大连接池数量
      maximum-pool-size: 30
      # 最小空闲线程数量
      minimum-idle: 5
      # 配置获取连接等待超时的时间
      connectionTimeout: 30000
      # 校验超时时间
      validationTimeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idleTimeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      maxLifetime: 1800000
      # 连接测试query（配置检测连接是否有效）
      connectionTestQuery: SELECT 1
      # 多久检查一次连接的活性
      keepaliveTime: 30000
    #    mysql数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.39:3306/dev-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: Lmh666...
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/dev-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true
#    username: root
#    password: xxd123456
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    properties:
      "hibernate.format_sql": true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      # 地址
      host: 192.168.2.39
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码(如没有密码请注释掉)
      # password:
      # 连接超时时间
      timeout: 10s
      # 是否开启ssl
      ssl:
        enabled: false

springdoc:
  #这里定义了两个分组，可定义多个，也可以不定义
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 1.演示模块
      packages-to-scan: com.sugarcoat
  swagger-ui:
    enabled: true
    path: /swagger-ui
    # 禁止默认路径
    disable-swagger-default-url: true

knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志配置
logging:
  level:
    "ROOT": info
    "org.hibernate.type.descriptor.sql.BasicBinder": TRACE

sugarcoat:
  cache:
    # redis key前缀
    keyPrefix: sugarcoat
    # 线程池数量
    threads: 4
    # Netty线程池数量
    nettyThreads: 8
    # 单节点配置
    singleServerConfig:
      # 客户端名称
      clientName: ${spring.application.name}
      # 最小空闲连接数
      connectionMinimumIdleSize: 8
      # 连接池大小
      connectionPoolSize: 32
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
# redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
  swagger:
    enable: true
    title: sugarcoat开发平台
    description: ""
    version: 1.0
    url: ""
    email: ""
    license: MIT
    license-url: ""




